import type { EcommerceAgentInput } from "./types";

export const sampleEcommerceAgentInput: EcommerceAgentInput = {
  store: {
    storeName: "Aurora Cup 独立站",
    platform: "Shopify",
    market: "美国",
    category: "智能温控/温显旅行杯",
    goal: "同时看销量、利润、广告回本、库存风险、退款/退货和竞品压力",
    userLevel: "beginner",
  },
  previousWeek: {
    label: "上周",
    startDate: "2026-07-06",
    endDate: "2026-07-12",
    products: [
      {
        productName: "Aurora Cup 黑色 500ml",
        sku: "CUP-BLACK-500",
        visitors: 4200,
        orders: 168,
        revenue: 6048,
        unitsSold: 176,
        adSpend: 1320,
        adRevenue: 3960,
        inventory: 320,
        grossProfit: 2419,
        refundOrders: 5,
        refundAmount: 180,
        refundReason: "杯盖漏水 / 温控不准",
      },
      {
        productName: "Aurora Cup 白色 500ml",
        sku: "CUP-WHITE-500",
        visitors: 3100,
        orders: 112,
        revenue: 4032,
        unitsSold: 118,
        adSpend: 980,
        adRevenue: 2580,
        inventory: 260,
        grossProfit: 1613,
        refundOrders: 3,
        refundAmount: 90,
        refundReason: "颜色有色差",
      },
      {
        productName: "Aurora Cup 礼盒套装",
        sku: "CUP-GIFT-SET",
        visitors: 1800,
        orders: 72,
        revenue: 4248,
        unitsSold: 74,
        adSpend: 620,
        adRevenue: 1980,
        inventory: 140,
        grossProfit: 1699,
        refundOrders: 2,
        refundAmount: 120,
        refundReason: "礼盒压痕",
      },
    ],
  },
  currentWeek: {
    label: "本周",
    startDate: "2026-07-13",
    endDate: "2026-07-19",
    products: [
      {
        productName: "Aurora Cup 黑色 500ml",
        sku: "CUP-BLACK-500",
        visitors: 4380,
        orders: 122,
        revenue: 4392,
        unitsSold: 128,
        adSpend: 1510,
        adRevenue: 2920,
        inventory: 118,
        grossProfit: 878,
        refundOrders: 4,
        refundAmount: 160,
        refundReason: "杯盖漏水 / 物流慢",
      },
      {
        productName: "Aurora Cup 白色 500ml",
        sku: "CUP-WHITE-500",
        visitors: 2940,
        orders: 95,
        revenue: 3420,
        unitsSold: 101,
        adSpend: 1040,
        adRevenue: 2210,
        inventory: 206,
        grossProfit: 1026,
        refundOrders: 3,
        refundAmount: 110,
        refundReason: "颜色有色差 / 预期不符",
      },
      {
        productName: "Aurora Cup 礼盒套装",
        sku: "CUP-GIFT-SET",
        visitors: 2160,
        orders: 86,
        revenue: 5074,
        unitsSold: 89,
        adSpend: 680,
        adRevenue: 2410,
        inventory: 42,
        grossProfit: 2030,
        refundOrders: 3,
        refundAmount: 180,
        refundReason: "礼盒压痕 / 送达太晚",
      },
    ],
  },
  competitors: [
    {
      name: "Ember Travel Mug 2",
      url: "https://ember.com/products/ember-travel-mug-2",
      source: "Ember 官方商品页",
      observedAt: "2026-07-22",
      price: 199.95,
      priceNote: "演示价，用于价格带分析；实际价格以页面为准",
      promotion: "高端温控旅行杯",
      rating: 4.7,
      reviews: 12000,
      keySellingPoints: ["精确温控", "最多 3 小时续航", "App 控制", "旅行场景"],
    },
    {
      name: "Nextmug Self-Heating Mug",
      url: "https://nextmug.com/",
      source: "Nextmug 官方 Shopify 店",
      observedAt: "2026-07-22",
      price: 99.95,
      priceNote: "官网 14 oz Nextmug sale price；实际价格以页面为准",
      promotion: "14 oz 促销价，强调不用 App",
      rating: 4.5,
      reviews: 2800,
      keySellingPoints: ["130/140/150°F 三档", "LED 状态灯", "长续航", "充电杯垫"],
    },
    {
      name: "VSITOO S3 Pro",
      url: "https://www.vsitoo.com/",
      source: "VSITOO 官方站",
      observedAt: "2026-07-22",
      price: 99.99,
      priceNote: "官网 S3 Pro from sale price；实际价格以页面为准",
      promotion: "AI 自加热，强调 120-150°F 自动控温",
      rating: 4.4,
      reviews: 1500,
      keySellingPoints: ["AI 饮品检测", "120-150°F 控温", "App 控制", "按键控制"],
    },
    {
      name: "Locckmy LED Temperature Water Bottle",
      url: "https://www.amazon.com/Locckmy-Temperature-Insulated-Stainless-AutomotiveTravel/dp/B085XHQ17Z",
      source: "Amazon 商品页",
      observedAt: "2026-07-22",
      price: 18.99,
      priceNote: "低价替代演示价；Amazon 页面当前可能没有 featured offer，实际价格以页面为准",
      promotion: "低价 LED 温显保温杯",
      rating: 4.1,
      reviews: 900,
      keySellingPoints: ["LED 温度显示", "50,000 次触摸", "防烫提醒", "真空保温"],
    },
  ],
};
